Style layout
DavidDontKnow/shoppers-on-the-go pull request #32
Opened 2023-02-13 00:30 UTC by myleen12

2023-02-13 01:07 UTC, DavidDontKnow requested changes
Please resolve merge conflicts

2023-02-13 01:17 UTC, myleen12 reviewed
body has been changed

2023-02-13 02:29 UTC, DavidDontKnow commented
It's still saying you have conflicts

2023-02-14 03:04 UTC, DavidDontKnow approved these changes

2023-02-14 03:04 UTC, merged